# Generated by Django 3.1 on 2020-08-29 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_info', models.TextField(help_text='Information about user', null=True)),
                ('profile_image', models.ImageField(upload_to='')),
                ('posts_amount', models.PositiveIntegerField(default=0, help_text='Total amount of posts written by current user')),
                ('comments_amount', models.PositiveIntegerField(default=0, help_text='Total amount of comments written by current user')),
                ('followers_amount', models.PositiveIntegerField(default=0, help_text='Total amount of user followers')),
                ('following_amount', models.PositiveIntegerField(default=0, help_text='Total amount of users those followed by current user')),
                ('user', models.OneToOneField(help_text='Primary key of user that holds current information', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_public_info',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interests',
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.IntegerField(choices=[(0, 'Following'), (1, 'Followed')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_follow_relation',
            },
        ),
    ]
