# Development only docker-compose file
# Production version will be placed in docker-compose-prod.yml

version: '3.7'

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - .:/code/
        depends_on:
            - db
    db:
        image: postgres:12
        volumes:
            - postgres_data:/var/lib/postgresql/postgres_data

volumes:
    postgres_data: